# TCL File Generated by Component Editor 18.1
# Tue Jan 08 10:24:37 CET 2019
# DO NOT MODIFY


# 
# Camera_Module "Camera_Module" v1.0
#  2019.01.08.10:24:37
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module Camera_Module
# 
set_module_property DESCRIPTION ""
set_module_property NAME Camera_Module
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Camera_Module
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Top_Level
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Top_Level.vhd VHDL PATH ../hdl/Top_Level.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_sink_1
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 avs_Address address Input 3
add_interface_port avalon_slave_0 avs_ChipSelect chipselect Input 1
add_interface_port avalon_slave_0 avs_Read read Input 1
add_interface_port avalon_slave_0 avs_Write write Input 1
add_interface_port avalon_slave_0 avs_ReadData readdata Output 32
add_interface_port avalon_slave_0 avs_WriteData writedata Input 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock ""
set_interface_property reset synchronousEdges NONE
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset Reset_n reset_n Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock_sink_1
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master AM_Adresse address Output 32
add_interface_port avalon_master AM_BurstCount burstcount Output 4
add_interface_port avalon_master AM_ByteEnable byteenable Output 4
add_interface_port avalon_master AM_DataRead readdata Input 32
add_interface_port avalon_master AM_DataWrite writedata Output 32
add_interface_port avalon_master AM_Read read Output 1
add_interface_port avalon_master AM_WaitRequest waitrequest Input 1
add_interface_port avalon_master AM_Write write Output 1
add_interface_port avalon_master AM_readdatavalid readdatavalid Input 1


# 
# connection point clock_sink_2
# 
add_interface clock_sink_2 clock end
set_interface_property clock_sink_2 clockRate 0
set_interface_property clock_sink_2 ENABLED true
set_interface_property clock_sink_2 EXPORT_OF ""
set_interface_property clock_sink_2 PORT_NAME_MAP ""
set_interface_property clock_sink_2 CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink_2 SVD_ADDRESS_GROUP ""

add_interface_port clock_sink_2 Clk_Camera clk Input 1


# 
# connection point Conduit_CAMERA_LCD
# 
add_interface Conduit_CAMERA_LCD conduit end
set_interface_property Conduit_CAMERA_LCD associatedClock clock_sink_1
set_interface_property Conduit_CAMERA_LCD associatedReset reset
set_interface_property Conduit_CAMERA_LCD ENABLED true
set_interface_property Conduit_CAMERA_LCD EXPORT_OF ""
set_interface_property Conduit_CAMERA_LCD PORT_NAME_MAP ""
set_interface_property Conduit_CAMERA_LCD CMSIS_SVD_VARIABLES ""
set_interface_property Conduit_CAMERA_LCD SVD_ADDRESS_GROUP ""

add_interface_port Conduit_CAMERA_LCD Buffer_Saved buffer_saved Output 2
add_interface_port Conduit_CAMERA_LCD Display_Buffer display_buffer Input 2


# 
# connection point clock_sink_1
# 
add_interface clock_sink_1 clock end
set_interface_property clock_sink_1 clockRate 0
set_interface_property clock_sink_1 ENABLED true
set_interface_property clock_sink_1 EXPORT_OF ""
set_interface_property clock_sink_1 PORT_NAME_MAP ""
set_interface_property clock_sink_1 CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink_1 SVD_ADDRESS_GROUP ""

add_interface_port clock_sink_1 Clk_FPGA clk Input 1


# 
# connection point Conduit_CAMERA
# 
add_interface Conduit_CAMERA conduit end
set_interface_property Conduit_CAMERA associatedClock clock_sink_2
set_interface_property Conduit_CAMERA associatedReset reset
set_interface_property Conduit_CAMERA ENABLED true
set_interface_property Conduit_CAMERA EXPORT_OF ""
set_interface_property Conduit_CAMERA PORT_NAME_MAP ""
set_interface_property Conduit_CAMERA CMSIS_SVD_VARIABLES ""
set_interface_property Conduit_CAMERA SVD_ADDRESS_GROUP ""

add_interface_port Conduit_CAMERA Data_Camera data_sensors_camera Input 12
add_interface_port Conduit_CAMERA Debug debug Output 32
add_interface_port Conduit_CAMERA FVAL input_fval Input 1
add_interface_port Conduit_CAMERA LVAL input_lval Input 1

